// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA88jgjhaYyx0Jr1-vOtQe8jq4nbSxcv6Y',
    appId: '1:194861914079:web:abcdef123456',
    messagingSenderId: '194861914079',
    projectId: 'dnotas-app',
    authDomain: 'dnotas-app.firebaseapp.com',
    storageBucket: 'dnotas-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA88jgjhaYyx0Jr1-vOtQe8jq4nbSxcv6Y',
    appId: '1:194861914079:android:0151647148c1fb4c54966a',
    messagingSenderId: '194861914079',
    projectId: 'dnotas-app',
    storageBucket: 'dnotas-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA88jgjhaYyx0Jr1-vOtQe8jq4nbSxcv6Y',
    appId: '1:194861914079:ios:8a9b7c6d5e4f3g2h1i0j',
    messagingSenderId: '194861914079',
    projectId: 'dnotas-app',
    storageBucket: 'dnotas-app.firebasestorage.app',
    iosBundleId: 'com.dnotas.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'demo-api-key-macos',
    appId: '1:123456789:macos:abcdef',
    messagingSenderId: '123456789',
    projectId: 'dnotas-demo',
    storageBucket: 'dnotas-demo.appspot.com',
    iosBundleId: 'com.dnotas.app',
  );
}